modLoader="javafml"
loaderVersion="[47,)"
license="${mod_license}"
issueTrackerURL="https://github.com/yigit-guven/easy-hammers/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://www.curseforge.com/api/v2/addon/484665/files"
displayURL="https://github.com/yigit-guven/easy-hammers"
logoFile="logo.png"
credits="Special thanks to the Minecraft community for inspiration and support."
authors="${mod_authors}"
description="${mod_description}"

[[dependencies.easy_hammers]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.easy_hammers]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
